<?php

namespace App\Lambda;

use Hammerstone\Sidecar\LambdaFunction;

class HelloWorld extends LambdaFunction
{

    public function handler()
    {
        // TODO: Implement handler() method.
        //pointer that tells laambda which method should be run.

    }

    public function package()
    {
        // Set of files that you want deoployed with this function
        return [
            'sidecar/index.js',
        ];
    }

    public function runtime()
    {
        return parent::runtime(); // TODO: Change the autogenerated stub
    }
}
